### PR TITLE
adds simple macro recordable functionality.

### PR DESCRIPTION
**Pull request by lacan**
adds a new menu to imageJ which makes it macro recordable using a GenericDialog.

### CODE REVIEW

**Comment by ctrueden** [comment]
@tinevez You OK with these changes? If so, let's merge it.

**Comment by ctrueden** [comment]
@lacan Note that your commits are not linked to your GitHub account, because they use an email address which is not associated with your account. To fix this, click a commit here, then click the question mark next to your name under the commit header.

**Comment by tinevez** [comment]
Yes I am!
Sorry for the delay.

**Comment by ctrueden** [comment]
Thanks guys!

**Pull request merged**
